### ISSUE TITLE
ImportError: cannot import name 'ROUGEScore' from 'torchmetrics.text' 

### ISSUE THREAD

**Issue by MLHafizur** [PacktPublishing/Practical-Deep-Learning-at-Scale-with-MLFlow#2]
ImportError                               Traceback (most recent call last)
Input In [13], in <cell line: 2>()
      1 from torchmetrics.text.rouge import ROUGEScore
----> 2 from flash.text import TextClassificationData, TextClassifier
      3 datamodule = TextClassificationData.from_csv(
      4     input_fields="review",
      5     target_fields="sentiment",
   (...)
      8     test_file="data/imdb/test.csv"
      9 )

File /anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/flash/text/__init__.py:3, in <module>
      1 from flash.text.classification import TextClassificationData, TextClassifier  # noqa: F401
      2 from flash.text.embedding import TextEmbedder  # noqa: F401
----> 3 from flash.text.question_answering import QuestionAnsweringData, QuestionAnsweringTask  # noqa: F401
      4 from flash.text.seq2seq import (  # noqa: F401
      5     Seq2SeqData,
      6     Seq2SeqTask,
   (...)
     10     TranslationTask,
     11 )

File /anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/flash/text/question_answering/__init__.py:2, in <module>
      1 from flash.text.question_answering.data import QuestionAnsweringData  # noqa: F401
----> 2 from flash.text.question_answering.model import QuestionAnsweringTask

File /anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/flash/text/question_answering/model.py:40, in <module>
     38 from flash.text.ort_callback import ORTCallback
     39 from flash.text.question_answering.finetuning import _get_question_answering_bacbones_for_freezing
---> 40 from flash.text.seq2seq.core.metrics import RougeMetric
     42 if _TEXT_AVAILABLE:
     43     from transformers import AutoModelForQuestionAnswering

File /anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/flash/text/seq2seq/core/metrics.py:25, in <module>
     23 from pytorch_lightning.utilities import rank_zero_deprecation
     24 from torchmetrics.text import BLEUScore as _BLEUScore
---> 25 from torchmetrics.text import ROUGEScore as _ROUGEScore
     27 _deprecated_text_metrics = partial(deprecated, deprecated_in="0.6.0", remove_in="0.7.0", stream=rank_zero_deprecation)
     30 class BLEUScore(_BLEUScore):

ImportError: cannot import name 'ROUGEScore' from 'torchmetrics.text' (/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torchmetrics/text/__init__.py)

**Comment by yliu2018** [comment]
Hi @MLHafizur , thanks for raising this issue. Which chapter's code did you have this problem? What's your virtual environment's pytorch-lightning flash version and torchmetrics version? This will help to determine if this is version related issues.
