### ISSUE TITLE
Errors while training on multiple GPUs

### ISSUE THREAD

**Issue by numericx** [PacktPublishing/Practical-Deep-Learning-at-Scale-with-MLFlow#3]
Hi!

I'm trying to run the code as-is from this repository but there are some errors if you try to train on multiple GPUs.

I've created the conda environment with the following commands: 

```
conda create --name dl_model python==3.8.10
conda activate dl_model
pip install -r requirements.txt
```

The result from conda list | grep lightning is:

```
lightning-bolts           0.5.0                    pypi_0    pypi
lightning-flash           0.5.0                    pypi_0    pypi
pytorch-lightning         1.4.9                    pypi_0    pypi
```
[ErrorMultipleGPUs.txt](https://github.com/PacktPublishing/Practical-Deep-Learning-at-Scale-with-MLFlow/files/9351999/ErrorMultipleGPUs.txt)

`RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "first_dl.py", line 23, in <module>
    trainer.finetune(classifier_model, datamodule=datamodule, strategy="freeze")
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/flash/core/trainer.py", line 165, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 158, in start_training
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/steeve/Anaconda3/envs/dl_model/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1`

nvidia-smi output is:

```
Tue Aug 16 10:40:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:05:00.0  On |                  N/A |
| 41%   71C    P0    70W / 250W |    633MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:06:00.0 Off |                  N/A |
| 28%   50C    P8    12W / 250W |     11MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:09:00.0 Off |                  N/A |
| 24%   43C    P8    10W / 250W |     11MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 23%   37C    P8     9W / 250W |     11MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by yliu2018** [comment]
Hi @numericx ,
Thanks for your information. I think this is indeed related to pytorch multi-gpu issue. Can you please try the following approach suggested in this thread and see if it works? Thanks!
https://stackoverflow.com/a/69907980
