### ISSUE TITLE
1062, "Duplicate entry 'mlflow.runName-f13c66c81dc842059edad4ee436e11f7' for key 'PRIMARY'"

### ISSUE THREAD

**Issue by elijah2352** [PacktPublishing/Practical-Deep-Learning-at-Scale-with-MLFlow#4]
Hello,

I am currently on chapter 3 and have started all of the containers for the mlflow tracking server. I can see minio, the mlflow server information, and mysql is running just fine. I am currently working on the notebook dl_model_tracking and am attempting to run cell 6:
`mlflow.pytorch.autolog()`
`with mlflow.start_run(experiment_id=experiment.experiment_id, run_name="chapter03") as dl_model_tracking_run:`
    `trainer.finetune(classifier_model, datamodule=datamodule, strategy="freeze")`
    `trainer.test()`

I am getting the error "BAD_REQUEST: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'mlflow.runName-f13c66c81dc842059edad4ee436e11f7' for key 'PRIMARY'")" [SQL: INSERT INTO tags....; however, when I peek into the mysql database at the tags table, it's empty. So there can't be a primary key already there if it's empty. Do you by chance know how to solve this? Thank you!

**Comment by elijah2352** [comment]
As an update, this is also occurring when I use postgreSQL as a backend and I am currently operating in a Windows environment with WSL 2.

**Comment by yliu2018** [comment]
@elijah2352 Thanks for reporting this issue. Which version of the MLflow are you using? It  might be a bug due to a recent update in MLflow.

**Comment by yliu2018** [comment]
MLflow 1.29 works fine so far. If you use any newer version, you might encounter these problems.
